spring:
  surrealdb:
    namespace: test
    database: test
    username: root
    password: root
    cache:
      enabled: true
      mode: memory
      namespace: cache
      database: main
      default-ttl: 10m

management:
  endpoints:
    web:
      exposure:
        include: health
